service: ocr

frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: ap-southeast-1

functions:
  ocr:
    handler: handler.ocr
    events:
      - http:
          path: /ocr
          method: get
    memorySize: 1536
    timeout: 30

plugins:
  - serverless-offline
